<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>net10.0</TargetFramework>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <!-- HtmlAgilityPack is a popular library for parsing HTML in .NET -->
  <ItemGroup>
    <PackageReference Include="HtmlAgilityPack" Version="1.11.72" />
  </ItemGroup>

</Project>
